// Indian market products with realistic pricing and attributes
const products = [
    // Essential Staples (Non-perishable, Divisible) - High Priority
    {
        id: 1,
        name: "Basmati Rice (5kg)",
        price: 400,
        originalPrice: 400,
        onSale: false,
        preference: 95,
        category: "grains",
        perishable: false,
        divisible: true,
        unit: "kg",
        deadline: 30,
        essential: true,
        monthlyNeed: 5
    },
    {
        id: 2,
        name: "Wheat Flour (10kg)",
        price: 350,
        originalPrice: 350,
        onSale: false,
        preference: 95,
        category: "grains",
        perishable: false,
        divisible: true,
        unit: "kg",
        deadline: 30,
        essential: true,
        monthlyNeed: 10
    },
    {
        id: 3,
        name: "Toor Dal (2kg)",
        price: 220,
        originalPrice: 280,
        onSale: true,
        preference: 90,
        category: "pulses",
        perishable: false,
        divisible: true,
        unit: "kg",
        deadline: 30,
        essential: true,
        monthlyNeed: 2
    },
    {
        id: 4,
        name: "Moong Dal (1kg)",
        price: 130,
        originalPrice: 130,
        onSale: false,
        preference: 85,
        category: "pulses",
        perishable: false,
        divisible: true,
        unit: "kg",
        deadline: 30,
        essential: true,
        monthlyNeed: 1
    },
    {
        id: 5,
        name: "Cooking Oil (2L)",
        price: 260,
        originalPrice: 300,
        onSale: true,
        preference: 90,
        category: "cooking",
        perishable: false,
        divisible: true,
        unit: "liter",
        deadline: 30,
        essential: true,
        monthlyNeed: 2
    },

    // Essential Vegetables (Weekly Purchase)
    {
        id: 6,
        name: "Onions (2kg)",
        price: 60,
        originalPrice: 60,
        onSale: false,
        preference: 85,
        category: "vegetables",
        perishable: true,
        divisible: true,
        unit: "kg",
        deadline: 7,
        essential: true,
        monthlyNeed: 8
    },
    {
        id: 7,
        name: "Potatoes (3kg)",
        price: 75,
        originalPrice: 75,
        onSale: false,
        preference: 80,
        category: "vegetables",
        perishable: true,
        divisible: true,
        unit: "kg",
        deadline: 10,
        essential: true,
        monthlyNeed: 12
    },
    {
        id: 8,
        name: "Tomatoes (2kg)",
        price: 80,
        originalPrice: 80,
        onSale: false,
        preference: 75,
        category: "vegetables",
        perishable: true,
        divisible: true,
        unit: "kg",
        deadline: 5,
        essential: true,
        monthlyNeed: 8
    },

    // Essential Spices & Condiments
    {
        id: 9,
        name: "Salt (1kg)",
        price: 25,
        originalPrice: 25,
        onSale: false,
        preference: 88,
        category: "spices",
        perishable: false,
        divisible: false,
        unit: "packet",
        deadline: 30,
        essential: true,
        monthlyNeed: 1
    },
    {
        id: 10,
        name: "Turmeric Powder",
        price: 40,
        originalPrice: 40,
        onSale: false,
        preference: 85,
        category: "spices",
        perishable: false,
        divisible: false,
        unit: "packet",
        deadline: 30,
        essential: true,
        monthlyNeed: 1
    },
    {
        id: 11,
        name: "Red Chili Powder",
        price: 60,
        originalPrice: 60,
        onSale: false,
        preference: 80,
        category: "spices",
        perishable: false,
        divisible: false,
        unit: "packet",
        deadline: 30,
        essential: true,
        monthlyNeed: 1
    },
    {
        id: 12,
        name: "Cumin Seeds",
        price: 80,
        originalPrice: 80,
        onSale: false,
        preference: 70,
        category: "spices",
        perishable: false,
        divisible: false,
        unit: "packet",
        deadline: 30,
        essential: false,
        monthlyNeed: 1
    },

    // Essential Dairy & Proteins
    {
        id: 13,
        name: "Milk (Daily - 30L)",
        price: 1500,
        originalPrice: 1500,
        onSale: false,
        preference: 90,
        category: "dairy",
        perishable: true,
        divisible: true,
        unit: "liter",
        deadline: 1,
        essential: true,
        monthlyNeed: 30
    },
    {
        id: 14,
        name: "Eggs (30 pieces)",
        price: 180,
        originalPrice: 200,
        onSale: true,
        preference: 88,
        category: "protein",
        perishable: true,
        divisible: true,
        unit: "pieces",
        deadline: 7,
        essential: true,
        monthlyNeed: 30
    },
    {
        id: 15,
        name: "Sugar (1kg)",
        price: 45,
        originalPrice: 45,
        onSale: false,
        preference: 75,
        category: "sweetener",
        perishable: false,
        divisible: true,
        unit: "kg",
        deadline: 30,
        essential: true,
        monthlyNeed: 1
    },

    // Additional Vegetables
    {
        id: 16,
        name: "Green Chilies (500g)",
        price: 30,
        originalPrice: 30,
        onSale: false,
        preference: 70,
        category: "vegetables",
        perishable: true,
        divisible: true,
        unit: "kg",
        deadline: 5,
        essential: true,
        monthlyNeed: 2
    },
    {
        id: 17,
        name: "Ginger (500g)",
        price: 60,
        originalPrice: 60,
        onSale: false,
        preference: 65,
        category: "vegetables",
        perishable: true,
        divisible: true,
        unit: "kg",
        deadline: 10,
        essential: true,
        monthlyNeed: 2
    },
    {
        id: 18,
        name: "Garlic (500g)",
        price: 40,
        originalPrice: 40,
        onSale: false,
        preference: 65,
        category: "vegetables",
        perishable: true,
        divisible: true,
        unit: "kg",
        deadline: 15,
        essential: true,
        monthlyNeed: 2
    },

    // Optional/Luxury Items
    {
        id: 19,
        name: "Red Label Tea",
        price: 45,
        originalPrice: 45,
        onSale: false,
        preference: 80,
        category: "beverages",
        perishable: false,
        divisible: false,
        unit: "packet",
        deadline: 30,
        essential: false,
        monthlyNeed: 1
    },
    {
        id: 20,
        name: "Parle-G Biscuits",
        price: 20,
        originalPrice: 25,
        onSale: true,
        preference: 75,
        category: "snacks",
        perishable: false,
        divisible: false,
        unit: "packet",
        deadline: 30,
        essential: false,
        monthlyNeed: 2
    },
    {
        id: 21,
        name: "Bananas (2kg)",
        price: 60,
        originalPrice: 60,
        onSale: false,
        preference: 70,
        category: "fruits",
        perishable: true,
        divisible: true,
        unit: "kg",
        deadline: 3,
        essential: false,
        monthlyNeed: 8
    },
    {
        id: 22,
        name: "Yogurt (1kg)",
        price: 80,
        originalPrice: 80,
        onSale: false,
        preference: 75,
        category: "dairy",
        perishable: true,
        divisible: true,
        unit: "kg",
        deadline: 3,
        essential: false,
        monthlyNeed: 4
    },
    {
        id: 23,
        name: "Chicken (1kg)",
        price: 200,
        originalPrice: 200,
        onSale: false,
        preference: 85,
        category: "protein",
        perishable: true,
        divisible: true,
        unit: "kg",
        deadline: 2,
        essential: false,
        monthlyNeed: 4
    },
    {
        id: 24,
        name: "Bread (Weekly)",
        price: 70,
        originalPrice: 70,
        onSale: false,
        preference: 70,
        category: "bakery",
        perishable: true,
        divisible: false,
        unit: "loaves",
        deadline: 3,
        essential: false,
        monthlyNeed: 4
    },
    {
        id: 25,
        name: "Maggi Noodles (Pack of 4)",
        price: 60,
        originalPrice: 60,
        onSale: false,
        preference: 60,
        category: "packaged",
        perishable: false,
        divisible: false,
        unit: "packet",
        deadline: 30,
        essential: false,
        monthlyNeed: 2
    }
]

const product = [/*... your full list (same as you posted) ...*/];

const userAddedItem = {
    id: 26,
    name: "Peanut Butter",
    price: 100,
    originalPrice: 120,
    onSale: true,
    preference: 90,
    category: "protein spread",
    perishable: false,
    divisible: false,
    unit: "jar",
    deadline: 30,
    essential: false,
    monthlyNeed: 1
};


const result = greedyOptimization(products, 1500, userAddedItem);

console.log("Optimized Shopping List:");
console.table(result.selectedItems);
console.log("Total Preference:", result.totalPreference);
console.log("Total Cost:", result.totalCost);
console.log("Efficiency (% of budget used):", result.efficiency);
console.log("Money Saved:", result.moneySaved);
